export interface IconEntry {
  emoji: string;
  keywords: string;
}

export const ICON_CATEGORIES: { label: string; icons: IconEntry[] }[] = [
  {
    label: "Docs",
    icons: [
      { emoji: "📄", keywords: "page document file" },
      { emoji: "📝", keywords: "note memo write" },
      { emoji: "📋", keywords: "clipboard list" },
      { emoji: "📌", keywords: "pin pinned" },
      { emoji: "📎", keywords: "paperclip attach" },
      { emoji: "🗂️", keywords: "folder index tab" },
      { emoji: "📁", keywords: "folder directory" },
      { emoji: "📂", keywords: "open folder" },
      { emoji: "🔖", keywords: "bookmark tag" },
      { emoji: "📜", keywords: "scroll document" },
      { emoji: "📃", keywords: "page document" },
      { emoji: "🗒️", keywords: "spiral notepad" },
    ],
  },
  {
    label: "Ideas",
    icons: [
      { emoji: "💡", keywords: "idea light bulb" },
      { emoji: "🚀", keywords: "rocket launch startup" },
      { emoji: "⚡", keywords: "lightning bolt fast" },
      { emoji: "🔥", keywords: "fire hot trending" },
      { emoji: "✨", keywords: "sparkles magic" },
      { emoji: "💫", keywords: "dizzy star spark" },
      { emoji: "🌟", keywords: "star glow bright" },
      { emoji: "🎯", keywords: "target goal aim" },
      { emoji: "🧠", keywords: "brain mind think" },
      { emoji: "🔮", keywords: "crystal ball vision" },
      { emoji: "🌈", keywords: "rainbow color" },
      { emoji: "🎪", keywords: "circus tent event" },
    ],
  },
  {
    label: "Work",
    icons: [
      { emoji: "💼", keywords: "briefcase work job" },
      { emoji: "🏢", keywords: "office building company" },
      { emoji: "🤝", keywords: "handshake deal partner" },
      { emoji: "📊", keywords: "chart bar graph data" },
      { emoji: "📈", keywords: "chart trend up growth" },
      { emoji: "📉", keywords: "chart trend down" },
      { emoji: "🗓️", keywords: "calendar schedule" },
      { emoji: "⏰", keywords: "alarm clock time" },
      { emoji: "🔑", keywords: "key access" },
      { emoji: "🏆", keywords: "trophy award win" },
      { emoji: "🎖️", keywords: "medal award" },
      { emoji: "💰", keywords: "money bag finance" },
    ],
  },
  {
    label: "Creative",
    icons: [
      { emoji: "🎨", keywords: "art palette paint" },
      { emoji: "✏️", keywords: "pencil draw edit" },
      { emoji: "🎬", keywords: "film clapper movie" },
      { emoji: "🎵", keywords: "music note audio" },
      { emoji: "📸", keywords: "camera photo" },
      { emoji: "🎭", keywords: "theater drama" },
      { emoji: "🖼️", keywords: "picture frame art" },
      { emoji: "🎹", keywords: "piano keyboard music" },
      { emoji: "🎸", keywords: "guitar music" },
      { emoji: "🎤", keywords: "microphone sing" },
      { emoji: "🎃", keywords: "halloween pumpkin" },
      { emoji: "🌸", keywords: "flower blossom" },
    ],
  },
  {
    label: "Learn",
    icons: [
      { emoji: "📚", keywords: "books study read" },
      { emoji: "🎓", keywords: "graduation school" },
      { emoji: "🔬", keywords: "microscope science" },
      { emoji: "🧪", keywords: "test tube experiment" },
      { emoji: "🧬", keywords: "dna biology" },
      { emoji: "🔭", keywords: "telescope space" },
      { emoji: "🗺️", keywords: "map world travel" },
      { emoji: "🧭", keywords: "compass direction" },
      { emoji: "🔍", keywords: "search magnify" },
      { emoji: "📡", keywords: "satellite antenna" },
      { emoji: "🌐", keywords: "globe web internet" },
      { emoji: "📐", keywords: "ruler geometry math" },
    ],
  },
  {
    label: "Life",
    icons: [
      { emoji: "❤️", keywords: "heart love" },
      { emoji: "🏠", keywords: "house home" },
      { emoji: "🌿", keywords: "plant leaf nature" },
      { emoji: "☕", keywords: "coffee tea drink" },
      { emoji: "🌙", keywords: "moon night" },
      { emoji: "⭐", keywords: "star favorite" },
      { emoji: "🎁", keywords: "gift present" },
      { emoji: "🏋️", keywords: "gym fitness workout" },
      { emoji: "🌊", keywords: "wave ocean water" },
      { emoji: "🦋", keywords: "butterfly nature" },
      { emoji: "🍀", keywords: "clover luck" },
      { emoji: "🐾", keywords: "paw pet animal" },
    ],
  },
];
